modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/MC-U-Team/Overworld-Mirror/issues"
displayURL="https://u-team.info/mods/overworldmirror"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="overworldmirror"
	version="${file.jarVersion}"
	displayName="Overworld Mirror"
	updateJSONURL="https://api.u-team.info/update/overworldmirror.json"
	description="This mod just mirrors the overworld and let you travel with a portal between them."
	
	[[dependencies.overworldmirror]]
	    modId="forge"
	    mandatory=true
	    versionRange="[47.0.16,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.overworldmirror]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.20.1]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.overworldmirror]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[5.1.2.266,)"
	    ordering="NONE"
	    side="BOTH"